[package]
name = "uds-fork"
version = "0.5.0"
description = """
A unix domain socket crate that supports abstract addresses, fd-passing and seqpacket sockets.
"""
readme = "README.md"
repository = "https://github.com/eesekaj/uds/tree/master"
license = "Apache-2.0 OR MIT"
authors = ["Torbj√∏rn Birch Moltu <t.b.moltu@lyse.net>", "Aleksandr Morozov <alex@nixd.org>"]
keywords = ["unix", "socket", "seqpacket", "abstract", "fdpassing"]
categories = ["os::unix-apis", "asynchronous"]
edition = "2024"
exclude = ["tests", "src/bin", ".vscode"]

[target."cfg(unix)".dependencies]
libc = "~0.2"


