[package]
name = "uds-fork"
version = "0.6.1"
description = """
A unix domain socket crate that supports abstract addresses, fd-passing, seqpacket and windows unix stream sockets.
"""
readme = "README.md"
repository = "https://github.com/eesekaj/uds"
license = "Apache-2.0 OR MIT"
authors = ["Torbj√∏rn Birch Moltu <t.b.moltu@lyse.net>", "Aleksandr Morozov <alex@nixd.org>"]
keywords = ["unix", "socket", "seqpacket", "fdpassing", "windows"]
categories = ["os::unix-apis", "asynchronous"]
edition = "2024"
exclude = ["tests", "src/bin", ".vscode"]

[target."cfg(unix)".dependencies]
libc = "~0.2"


[target.'cfg(windows)'.dependencies.windows-sys]
version = "~0.61"
features = [
  "Win32_Foundation",
  "Win32_Networking_WinSock",
  "Win32_System_IO",
]

